# Generated by Django 6.0.7 on 2026-08-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-created_at'], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(help_text='Unique asset identifier (e.g. AST-001)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='building',
            field=models.CharField(help_text='Campus building where the asset is located (e.g. Main Block)', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('IT & Computers', 'IT & Computers'), ('Lab Equipment', 'Lab Equipment'), ('Classroom & Furniture', 'Classroom & Furniture'), ('Audio / Visual', 'Audio / Visual'), ('Electrical & Utilities', 'Electrical & Utilities'), ('Other', 'Other')], default='IT & Computers', help_text='Department or category of asset', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, help_text='Additional specifications or notes about the asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(help_text='Name or model of the asset (e.g. Dell Desktop PC)', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='Date when this asset was acquired', null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='room',
            field=models.CharField(blank=True, help_text='Room or Lab number (e.g. Room 204, Lab 3B)', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('IN_STOCK', 'In Stock'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('DAMAGED', 'Damaged'), ('RETIRED', 'Retired')], default='ACTIVE', help_text='Current condition and availability status', max_length=30),
        ),
    ]
