# Generated by Django 6.0.7 on 2026-09-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_options_alter_asset_asset_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_code',
            field=models.CharField(blank=True, help_text='Unique asset identifier (e.g. AST-0001). Leave blank to auto-generate.', max_length=20, unique=True),
        ),
    ]
