# Generated by Django 6.0.7 on 2026-09-14 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_asset_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the campus location (e.g. Computer Science Block, Computer Lab 1)', max_length=150)),
                ('location_type', models.CharField(choices=[('CAMPUS', 'Campus'), ('BLOCK', 'Block / Building'), ('DEPARTMENT', 'Department / Area'), ('CLASSROOM', 'Classroom'), ('COMPUTER_LAB', 'Computer Lab'), ('LABORATORY', 'Laboratory'), ('HALL', 'Seminar / Conference Hall'), ('OFFICE', 'Office'), ('LIBRARY', 'Library'), ('SERVER_ROOM', 'Server Room'), ('STORE_ROOM', 'Store Room'), ('MAINTENANCE_ROOM', 'Maintenance Room'), ('STAFF_ROOM', 'Staff Room'), ('OTHER', 'Other Area')], default='CLASSROOM', help_text='Category of campus location', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional notes or directions for this location')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this location is active and available for assignment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent building or block for hierarchical sorting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.location')),
            ],
            options={
                'verbose_name': 'Campus Location',
                'verbose_name_plural': 'Campus Locations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Centralized campus location where the asset is registered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.location'),
        ),
    ]
