# Generated by Django 6.0.7 on 2026-08-31 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_options_alter_asset_asset_code_and_more'),
        ('complaints', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='assets.asset', verbose_name='Affected Asset'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assigned Date'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_notes',
            field=models.TextField(blank=True, verbose_name='Resolution Notes'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resolved Date'),
        ),
        migrations.CreateModel(
            name='ComplaintResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField(default=1, verbose_name='Quantity Used')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Used')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_used', to='complaints.complaint', verbose_name='Complaint')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaint_usages', to='inventory.inventoryitem', verbose_name='Inventory Item')),
            ],
            options={
                'verbose_name': 'Complaint Resource',
                'verbose_name_plural': 'Complaint Resources',
                'ordering': ['-used_at'],
            },
        ),
    ]
