# Generated by Django 6.0.7 on 2026-09-06 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_asset_complaint_assigned_at_and_more'),
        ('inventory', '0002_inventoryitem_storage_location_stocktransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='inspection_notes',
            field=models.TextField(blank=True, verbose_name='Inspection Notes'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Assigned', 'Assigned'), ('Under Inspection', 'Under Inspection'), ('Action Required', 'Action Required'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Submitted', max_length=30, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ComplaintHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30, verbose_name='Status')),
                ('comment', models.TextField(blank=True, verbose_name='Notes / Comment')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed By')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='complaints.complaint', verbose_name='Complaint')),
            ],
            options={
                'verbose_name': 'Complaint History',
                'verbose_name_plural': 'Complaint Histories',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('UNAVAILABLE_RESOURCE', 'Unavailable Inventory Resource Required'), ('PURCHASE', 'Purchase New Item / Resource'), ('ASSET_REPAIR', 'Asset Repair Required'), ('ASSET_REPLACE', 'Asset Replacement Recommended'), ('ASSET_RETIRE', 'Asset Retirement Recommended'), ('OTHER', 'Other Administrative Action Required')], default='UNAVAILABLE_RESOURCE', max_length=30, verbose_name='Request Type')),
                ('quantity_requested', models.PositiveIntegerField(default=1, verbose_name='Quantity Requested')),
                ('reason', models.TextField(verbose_name='Reason / Findings')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Admin Decision'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('MORE_INFO', 'More Info Requested')], default='PENDING', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Administrator Notes')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Decided Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='complaints.complaint', verbose_name='Complaint')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_maintenance_requests', to=settings.AUTH_USER_MODEL, verbose_name='Decided By')),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to='inventory.inventoryitem', verbose_name='Requested Inventory Item')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Maintenance Request',
                'verbose_name_plural': 'Maintenance Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
