# Generated by Django 6.0.7 on 2026-09-14 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_location_asset_location'),
        ('complaints', '0003_complaint_inspection_notes_alter_complaint_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='location_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='assets.location', verbose_name='Structured Location'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='manual_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Additional / Manual Location Details'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Location'),
        ),
    ]
