# Generated by Django 6.0.7 on 2026-09-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_location_record_complaint_manual_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='Rejection Reason'),
        ),
    ]
