# Generated by Django 6.1 on 2026-09-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0005_complaint_rejection_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("Submitted", "Submitted"),
                    ("Under Review", "Under Review"),
                    ("Assigned", "Assigned"),
                    ("Accepted", "Accepted"),
                    ("Under Inspection", "Under Inspection"),
                    ("Action Required", "Action Required"),
                    ("In Progress", "In Progress"),
                    ("Resolved", "Resolved"),
                    ("Closed", "Closed"),
                ],
                default="Submitted",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
