# Generated by Django 6.1 on 2026-09-16 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_alter_activity_timestamp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("ASSIGNMENT", "New assignment"),
                            ("REASSIGNMENT", "Reassignment"),
                            ("REQUEST_APPROVED", "Request approved"),
                            ("REQUEST_REJECTED", "Request rejected"),
                            ("REQUEST_MORE_INFO", "More info requested"),
                        ],
                        default="ASSIGNMENT",
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                (
                    "link",
                    models.CharField(blank=True, max_length=500, verbose_name="Link"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Read")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
