# Generated by Django 6.0.7 on 2026-09-06 08:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_asset_code'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='storage_location',
            field=models.CharField(blank=True, help_text='Storage room or warehouse location (e.g. Central Store, Room 105)', max_length=100),
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RECEIVE', 'Stock Received / Added'), ('ISSUE', 'Stock Issued / Consumed'), ('ADJUSTMENT', 'Stock Adjustment')], default='RECEIVE', max_length=20)),
                ('quantity', models.PositiveIntegerField(help_text='Number of units for this transaction', validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True, help_text='Reason for issue, invoice number, or maintenance notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, help_text='Optional asset associated with this inventory usage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='assets.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
