# Generated by Django 6.0.7 on 2026-08-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campus_id',
            field=models.CharField(blank=True, help_text='Student Roll Number or Faculty/Staff Employee ID.', max_length=50, verbose_name='Campus / Roll / Employee ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty / Teacher'), ('STAFF', 'Staff / Maintenance'), ('ADMIN', 'Administrator')], default='STUDENT', help_text='Designates the campus role and authorization level of the user.', max_length=20, verbose_name='Role'),
        ),
    ]
