# Generated by Django 6.0.7 on 2026-08-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year_or_semester',
            field=models.CharField(blank=True, help_text='e.g. 3rd Year / Semester 5 (for students).', max_length=50, verbose_name='Year / Semester'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty / Teacher'), ('MAINTENANCE', 'Maintenance Staff'), ('ADMIN', 'Administrator')], default='STUDENT', help_text='Designates the campus role and authorization level of the user.', max_length=20, verbose_name='Role'),
        ),
    ]
