# Generated by Django 6.0.7 on 2026-09-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_year_or_semester_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Designates whether maintenance staff is available for new assignments.', verbose_name='Available for Assignment'),
        ),
    ]
