# Generated by Django 6.0.7 on 2026-09-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('MAINTENANCE', 'Maintenance Staff'), ('ADMIN', 'Administrator')], default='STUDENT', help_text='Designates the campus role and authorization level of the user.', max_length=20, verbose_name='Role'),
        ),
    ]
