# Generated by Django 6.1 on 2026-09-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="specialization",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Electrical", "Electrical"),
                    ("Plumbing", "Plumbing"),
                    ("Furniture", "Furniture"),
                    ("Cleanliness", "Cleanliness"),
                    ("IT / Network", "IT / Network"),
                    ("Other", "Other"),
                ],
                default="Other",
                help_text="Maintenance specialization used for specialization-first staff assignment.",
                max_length=50,
                verbose_name="Specialization",
            ),
        ),
    ]
